# TCL File Generated by Component Editor 12.0
# Tue Aug 28 15:27:00 PDT 2012
# DO NOT MODIFY


# 
# stream_writer "stream_writer" v1.0
# null 2012.08.28.15:27:00
# 
# 

# 
# request TCL package from ACDS 12.0
# 
package require -exact qsys 12.0


# 
# module stream_writer
# 
set_module_property NAME stream_writer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME "Stream Writer"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property ELABORATION_CALLBACK elaboration_callback


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL stream_writer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file stream_writer/util_pkg.vhd VHDL PATH util_pkg.vhd
add_fileset_file stream_writer/architecture_pkg.vhd VHDL PATH architecture_pkg.vhd
add_fileset_file stream_writer/component_pkg.vhd VHDL PATH component_pkg.vhd
add_fileset_file stream_writer/fwft_fifo_reg.vhd VHDL PATH fwft_fifo_reg.vhd
add_fileset_file stream_writer/buffer_list.vhd VHDL PATH buffer_list.vhd
add_fileset_file stream_writer/stream_writer.vhd VHDL PATH stream_writer.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL stream_writer
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file stream_writer/util_pkg.vhd VHDL PATH util_pkg.vhd
add_fileset_file stream_writer/architecture_pkg.vhd VHDL PATH architecture_pkg.vhd
add_fileset_file stream_writer/component_pkg.vhd VHDL PATH component_pkg.vhd
add_fileset_file stream_writer/fwft_fifo_reg.vhd VHDL PATH fwft_fifo_reg.vhd
add_fileset_file stream_writer/buffer_list.vhd VHDL PATH buffer_list.vhd
add_fileset_file stream_writer/stream_writer.vhd VHDL PATH stream_writer.vhd


# 
# parameters
# 
add_parameter STREAM_DATA_WIDTH_BITS POSITIVE 24
set_parameter_property STREAM_DATA_WIDTH_BITS DEFAULT_VALUE 24
set_parameter_property STREAM_DATA_WIDTH_BITS DISPLAY_NAME STREAM_DATA_WIDTH_BITS
set_parameter_property STREAM_DATA_WIDTH_BITS TYPE POSITIVE
set_parameter_property STREAM_DATA_WIDTH_BITS UNITS None
set_parameter_property STREAM_DATA_WIDTH_BITS ALLOWED_RANGES 1:1024
set_parameter_property STREAM_DATA_WIDTH_BITS AFFECTS_GENERATION false
set_parameter_property STREAM_DATA_WIDTH_BITS HDL_PARAMETER true

add_parameter MEMORY_DATA_WIDTH_BYTES POSITIVE 4
set_parameter_property MEMORY_DATA_WIDTH_BYTES DEFAULT_VALUE 4
set_parameter_property MEMORY_DATA_WIDTH_BYTES DISPLAY_NAME MEMORY_DATA_WIDTH_BYTES
set_parameter_property MEMORY_DATA_WIDTH_BYTES TYPE POSITIVE
set_parameter_property MEMORY_DATA_WIDTH_BYTES UNITS None
set_parameter_property MEMORY_DATA_WIDTH_BYTES ALLOWED_RANGES 1:128
set_parameter_property MEMORY_DATA_WIDTH_BYTES AFFECTS_GENERATION false
set_parameter_property MEMORY_DATA_WIDTH_BYTES HDL_PARAMETER true

add_parameter LOG2_MEMORY_BURST_BEATS NATURAL 3
set_parameter_property LOG2_MEMORY_BURST_BEATS DEFAULT_VALUE 3
set_parameter_property LOG2_MEMORY_BURST_BEATS DISPLAY_NAME LOG2_MEMORY_BURST_BEATS
set_parameter_property LOG2_MEMORY_BURST_BEATS TYPE NATURAL
set_parameter_property LOG2_MEMORY_BURST_BEATS UNITS None
set_parameter_property LOG2_MEMORY_BURST_BEATS ALLOWED_RANGES 0:7
set_parameter_property LOG2_MEMORY_BURST_BEATS AFFECTS_GENERATION false
set_parameter_property LOG2_MEMORY_BURST_BEATS HDL_PARAMETER true

add_parameter BUFFER_LIST_ENTRIES POSITIVE 8
set_parameter_property BUFFER_LIST_ENTRIES DEFAULT_VALUE 8
set_parameter_property BUFFER_LIST_ENTRIES DISPLAY_NAME BUFFER_LIST_ENTRIES
set_parameter_property BUFFER_LIST_ENTRIES TYPE POSITIVE
set_parameter_property BUFFER_LIST_ENTRIES UNITS None
set_parameter_property BUFFER_LIST_ENTRIES ALLOWED_RANGES 8:64
set_parameter_property BUFFER_LIST_ENTRIES AFFECTS_GENERATION false
set_parameter_property BUFFER_LIST_ENTRIES HDL_PARAMETER true

add_parameter CAPTURE_STARTOFPACKET_DATA NATURAL 0
set_parameter_property CAPTURE_STARTOFPACKET_DATA DEFAULT_VALUE 0
set_parameter_property CAPTURE_STARTOFPACKET_DATA DISPLAY_NAME CAPTURE_STARTOFPACKET_DATA
set_parameter_property CAPTURE_STARTOFPACKET_DATA TYPE NATURAL
set_parameter_property CAPTURE_STARTOFPACKET_DATA UNITS None
set_parameter_property CAPTURE_STARTOFPACKET_DATA ALLOWED_RANGES 0:1
set_parameter_property CAPTURE_STARTOFPACKET_DATA AFFECTS_GENERATION false
set_parameter_property CAPTURE_STARTOFPACKET_DATA HDL_PARAMETER true



# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressAlignment DYNAMIC
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave isMemoryDevice true
set_interface_property slave isNonVolatileStorage false
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 32
set_interface_property slave printableDevice false
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true

add_interface_port slave slave_waitrequest waitrequest Output 1
add_interface_port slave slave_address address Input 3
add_interface_port slave slave_read read Input 1
add_interface_port slave slave_write write Input 1
add_interface_port slave slave_writedata writedata Input 32
add_interface_port slave slave_readdatavalid readdatavalid Output 1
add_interface_port slave slave_readdata readdata Output 32


# +-----------------------------------
# | connection point interrupt_sender
# | 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint slave
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset

set_interface_property interrupt_sender ENABLED true

add_interface_port interrupt_sender interrupt irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point streaming_sink
# | 
add_interface streaming_sink avalon_streaming end
set_interface_property streaming_sink associatedClock clock
set_interface_property streaming_sink associatedReset reset
set_interface_property streaming_sink dataBitsPerSymbol 8
set_interface_property streaming_sink errorDescriptor ""
set_interface_property streaming_sink firstSymbolInHighOrderBits true
set_interface_property streaming_sink maxChannel 0
set_interface_property streaming_sink readyLatency 1

set_interface_property streaming_sink ENABLED true

add_interface_port streaming_sink sink_valid valid Input 1
add_interface_port streaming_sink sink_startofpacket startofpacket Input 1
add_interface_port streaming_sink sink_endofpacket endofpacket Input 1
add_interface_port streaming_sink sink_data data Input stream_data_width_bits
add_interface_port streaming_sink sink_ready ready Output 1
# | 
# +-----------------------------------

# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master constantBurstBehavior 1
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true

add_interface_port avalon_master master_waitrequest waitrequest Input 1
add_interface_port avalon_master master_burstcount burstcount Output log2_memory_burst_beats+1
add_interface_port avalon_master master_address address Output 32
add_interface_port avalon_master master_write write Output 1
add_interface_port avalon_master master_writedata writedata Output memory_data_width_bytes*8
add_interface_port avalon_master master_byteenable byteenable Output memory_data_width_bytes

###########################################################################
proc elaboration_callback {} {

    set_module_assignment embeddedsw.CMacro.STREAM_DATA_WIDTH_BITS     [get_parameter_value STREAM_DATA_WIDTH_BITS]
    set_module_assignment embeddedsw.CMacro.MEMORY_DATA_WIDTH_BYTES    [get_parameter_value MEMORY_DATA_WIDTH_BYTES]
    set_module_assignment embeddedsw.CMacro.LOG2_MEMORY_BURST_BEATS    [get_parameter_value LOG2_MEMORY_BURST_BEATS]
    set_module_assignment embeddedsw.CMacro.BUFFER_LIST_ENTRIES        [get_parameter_value BUFFER_LIST_ENTRIES]
    set_module_assignment embeddedsw.CMacro.CAPTURE_STARTOFPACKET_DATA [get_parameter_value CAPTURE_STARTOFPACKET_DATA]
}

